modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Timefall Development License 1.2"

[[mods]]
modId = "simplybows"
version = "${version}"
displayName = "Simply Bows"
authors = "Sweenus, Hootea"
description = '''

'''
logoFile = "assets/simplybows/icon.png"

[[dependencies.simplybows]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplybows]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplybows]]
modId = "architectury"
mandatory = true
versionRange = "[9,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "simplybows.mixins.json"
